name: rss_alert_flutter
version: 1.0.0+1
description: 國家級警報自動推播 App
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_local_notifications: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true 